/**
 * Instrument worklist generators.
 *
 * All generators consume the SAME calculated reaction (from reactionMath), so a
 * volume on the Opentrons deck, in a Hamilton CSV and in the Excel sheet is
 * always the same number from the same derivation.
 *
 * Formats:
 *   - Opentrons Python Protocol API v2 (runnable on OT-2 / Flex; simulate first)
 *   - Hamilton Venus-style CSV  (SourceLabware,SourcePosition,TargetLabware,TargetPosition,Volume)
 *   - Tecan EVOware GWL (worklist: A;source;;;pos;;vol / D;dest;;;pos;;vol / W;)
 *   - Labcyte/Beckman Echo picklist CSV (Source Plate Name,Source Well,Destination Plate Name,Destination Well,Transfer Volume)
 */

import { ReactionCalculation, MasterMixResult } from './reactionMath';

export interface PlateDesign {
  rows: number;          // 8 for 96-well, 16 for 384
  cols: number;          // 12 or 24
  /** Ordered destination wells. If omitted, filled column-major A1,B1,...,H1,A2,... */
  wells?: string[];
  reactionCount: number;
}

export interface WorklistBundle {
  opentronsPy: string;
  hamiltonCsv: string;
  tecanGwl: string;
  echoCsv: string;
  /** Machine-readable summary the UI shows alongside downloads. */
  summary: {
    reactionCount: number;
    masterMixTubeVolumeMicroliters: number;
    perTubeComponents: { name: string; volPerRxnMicroliters: number }[];
    destinationWells: string[];
    warnings: string[];
  };
}

const ROW_LETTERS = 'ABCDEFGHIJKLMNOP';

export function generateWells(rows: number, cols: number, count: number): string[] {
  const out: string[] = [];
  for (let c = 1; c <= cols && out.length < count; c++) {
    for (let r = 0; r < rows && out.length < count; r++) {
      out.push(`${ROW_LETTERS[r]}${c}`);
    }
  }
  return out;
}

/** Sanitise a free-text name for use as a Python identifier or CSV token. */
function slug(s: string): string {
  return String(s || '').replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '').replace(/^(\d)/, '_$1') || 'item';
}

function csvEscape(s: string): string {
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function buildWorklists(
  calc: ReactionCalculation,
  mm: MasterMixResult,
  plate: PlateDesign,
  meta: { protocolTitle: string; documentId?: string; version?: string }
): WorklistBundle {
  const warnings: string[] = [];
  const n = Math.max(0, Math.floor(plate.reactionCount));
  const wells = plate.wells && plate.wells.length >= n ? plate.wells.slice(0, n) : generateWells(plate.rows, plate.cols, n);
  if (wells.length < n) warnings.push(`Plate has ${plate.rows * plate.cols} wells but ${n} reactions were requested; only ${wells.length} are mapped.`);

  const mixPerRxn = mm.masterMixVolumePerReaction;
  const perTube = mm.lines.filter((l) => !l.includedInMix && l.volPerRxnMicroliters > 0);
  const mixLines = mm.lines.filter((l) => l.includedInMix && l.volPerRxnMicroliters > 0);

  if (mixPerRxn <= 0) warnings.push('Master mix volume per reaction is zero — nothing to dispense.');
  if (mixPerRxn > 0 && mixPerRxn < 1) warnings.push(`Master mix dispense volume ${mixPerRxn} µL is below the reliable range for most air-displacement heads.`);

  const plateType = plate.rows * plate.cols >= 384 ? 384 : 96;
  const src = 'reagent_tubes';
  const dst = 'reaction_plate';

  // ---------------------------------------------------------------- Opentrons
  const componentTubes = mixLines.map((l, i) => ({ ...l, tube: `${ROW_LETTERS[i % 4]}${Math.floor(i / 4) + 1}` }));
  const perTubeTubes = perTube.map((l, i) => ({ ...l, tube: `${ROW_LETTERS[(i + componentTubes.length) % 4]}${Math.floor((i + componentTubes.length) / 4) + 1}` }));
  const mixTube = `${ROW_LETTERS[(componentTubes.length + perTubeTubes.length) % 4]}${Math.floor((componentTubes.length + perTubeTubes.length) / 4) + 1}`;

  const py = `# ${meta.protocolTitle}
# ${meta.documentId ?? ''} ${meta.version ? 'v' + meta.version : ''}
# Generated by BioSOP Generator. SIMULATE BEFORE RUNNING:  opentrons_simulate this_file.py
# Volumes are identical to the protocol's Excel/Word reaction sheet (same calculation engine).

from opentrons import protocol_api

metadata = {
    "protocolName": ${JSON.stringify(meta.protocolTitle)},
    "author": "BioSOP Generator",
    "description": "Master mix assembly and plate dispense",
}
requirements = {"robotType": "OT-2", "apiLevel": "2.16"}

# ---- Design ----
N_REACTIONS = ${n}
MIX_PER_RXN_UL = ${mixPerRxn}
DEST_WELLS = ${JSON.stringify(wells)}

# Master mix components (µL for the whole run, includes overflow)
MIX_COMPONENTS = [
${componentTubes.map((c) => `    {"name": ${JSON.stringify(c.name)}, "tube": "${c.tube}", "vol_ul": ${c.volForRunMicroliters}},`).join('\n')}
]
MIX_TUBE = "${mixTube}"

# Per-tube components (added to each reaction individually — NOT in the mix)
PER_TUBE = [
${perTubeTubes.map((c) => `    {"name": ${JSON.stringify(c.name)}, "tube": "${c.tube}", "vol_ul": ${c.volPerRxnMicroliters}},`).join('\n')}
]


def run(protocol: protocol_api.ProtocolContext):
    tips20 = protocol.load_labware("opentrons_96_tiprack_20ul", "1")
    tips300 = protocol.load_labware("opentrons_96_tiprack_300ul", "4")
    tubes = protocol.load_labware("opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap", "2")
    plate = protocol.load_labware("${plateType === 384 ? 'corning_384_wellplate_112ul_flat' : 'nest_96_wellplate_100ul_pcr_full_skirt'}", "3")
    p20 = protocol.load_instrument("p20_single_gen2", "left", tip_racks=[tips20])
    p300 = protocol.load_instrument("p300_single_gen2", "right", tip_racks=[tips300])

    def pick(vol):
        return p20 if vol <= 20 else p300

    # 1. Assemble master mix
    protocol.comment("Assembling master mix into tube " + MIX_TUBE)
    for c in MIX_COMPONENTS:
        pip = pick(c["vol_ul"])
        pip.transfer(c["vol_ul"], tubes[c["tube"]], tubes[MIX_TUBE], new_tip="always",
                     mix_after=(3, min(c["vol_ul"], pip.max_volume)) if c is MIX_COMPONENTS[-1] else None)

    # 2. Dispense mix to plate
    protocol.comment(f"Dispensing {MIX_PER_RXN_UL} uL mix to {len(DEST_WELLS)} wells")
    pip = pick(MIX_PER_RXN_UL)
    pip.distribute(MIX_PER_RXN_UL, tubes[MIX_TUBE], [plate[w] for w in DEST_WELLS],
                   new_tip="once", disposal_volume=pip.min_volume)

    # 3. Add per-tube components to each well
    for c in PER_TUBE:
        protocol.comment("Adding " + c["name"])
        pip = pick(c["vol_ul"])
        for w in DEST_WELLS:
            pip.transfer(c["vol_ul"], tubes[c["tube"]], plate[w], new_tip="always", mix_after=(2, c["vol_ul"]))

    protocol.comment("Done. Seal and proceed to thermal profile.")
`;

  // ---------------------------------------------------------------- Hamilton
  const hamRows: string[] = ['SourceLabware,SourcePosition,TargetLabware,TargetPosition,Volume,LiquidClass,Comment'];
  for (const c of componentTubes) {
    hamRows.push([src, c.tube, src, mixTube, c.volForRunMicroliters.toFixed(2), 'HighVolume_Water_DispenseJet_Empty', `mix: ${c.name}`].map(csvEscape).join(','));
  }
  for (const w of wells) {
    hamRows.push([src, mixTube, dst, w, mixPerRxn.toFixed(2), 'StandardVolume_Water_DispenseSurface_Empty', 'master mix'].map(csvEscape).join(','));
  }
  for (const c of perTubeTubes) {
    for (const w of wells) {
      hamRows.push([src, c.tube, dst, w, c.volPerRxnMicroliters.toFixed(2), 'LowVolume_Water_DispenseSurface_Empty', c.name].map(csvEscape).join(','));
    }
  }

  // ---------------------------------------------------------------- Tecan GWL
  const gwl: string[] = [`C;${meta.protocolTitle}`, `C;Generated by BioSOP Generator ${meta.documentId ?? ''}`];
  const wellIndex = (w: string) => {
    const r = ROW_LETTERS.indexOf(w[0]);
    const c = parseInt(w.slice(1), 10);
    return (c - 1) * plate.rows + r + 1; // column-major 1-based, Tecan convention
  };
  // Source is a 24-position tube rack (4 rows x 6 cols), independent of the plate geometry.
  const TUBE_RACK_ROWS = 4;
  const tubeIndex = (t: string) => {
    const r = ROW_LETTERS.indexOf(t[0]);
    const c = parseInt(t.slice(1), 10);
    return (c - 1) * TUBE_RACK_ROWS + r + 1;
  };
  for (const c of componentTubes) {
    gwl.push(`A;${src};;;${tubeIndex(c.tube)};;${c.volForRunMicroliters.toFixed(1)};;;;`);
    gwl.push(`D;${src};;;${tubeIndex(mixTube)};;${c.volForRunMicroliters.toFixed(1)};;;;`);
    gwl.push('W;');
  }
  for (const w of wells) {
    gwl.push(`A;${src};;;${tubeIndex(mixTube)};;${mixPerRxn.toFixed(1)};;;;`);
    gwl.push(`D;${dst};;;${wellIndex(w)};;${mixPerRxn.toFixed(1)};;;;`);
    gwl.push('W;');
  }
  for (const c of perTubeTubes) {
    for (const w of wells) {
      gwl.push(`A;${src};;;${tubeIndex(c.tube)};;${c.volPerRxnMicroliters.toFixed(1)};;;;`);
      gwl.push(`D;${dst};;;${wellIndex(w)};;${c.volPerRxnMicroliters.toFixed(1)};;;;`);
      gwl.push('W;');
    }
  }

  // ---------------------------------------------------------------- Echo (nL, 2.5 nL increments)
  const echo: string[] = ['Source Plate Name,Source Well,Destination Plate Name,Destination Well,Transfer Volume'];
  const toNl = (ul: number) => Math.round((ul * 1000) / 2.5) * 2.5;
  let echoWarned = false;
  for (const c of perTubeTubes) {
    for (const w of wells) {
      const nl = toNl(c.volPerRxnMicroliters);
      if (nl > 5000 && !echoWarned) { warnings.push('Echo transfers above ~5 µL are impractical; use the Echo picklist for low-volume additions only.'); echoWarned = true; }
      echo.push(['source_384LDV', c.tube, dst, w, String(nl)].map(csvEscape).join(','));
    }
  }
  if (echo.length === 1) echo.push('# No per-tube (low-volume) transfers in this protocol; master-mix dispensing is better suited to a tip-based handler.');

  return {
    opentronsPy: py,
    hamiltonCsv: hamRows.join('\n') + '\n',
    tecanGwl: gwl.join('\n') + '\n',
    echoCsv: echo.join('\n') + '\n',
    summary: {
      reactionCount: n,
      masterMixTubeVolumeMicroliters: mm.masterMixTotalVolume,
      perTubeComponents: perTube.map((l) => ({ name: l.name, volPerRxnMicroliters: l.volPerRxnMicroliters })),
      destinationWells: wells,
      warnings,
    },
  };
}
